# Generated by Django 5.2.14 on 2026-05-07 06:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='노드 고유 식별자 (UUID v4)', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='노드의 WGS 84 좌표 (경도, 위도)', srid=4326, verbose_name='좌표(Point)')),
                ('name', models.CharField(blank=True, default='', help_text='교차로명, 건물 출입구명 등 사람이 읽을 수 있는 이름', max_length=200, verbose_name='지점 이름')),
                ('floor', models.IntegerField(default=1, help_text='해당 노드가 위치한 층 (지상 1층 = 1, 지하 1층 = -1)', verbose_name='층 수')),
                ('is_entrance', models.BooleanField(default=False, help_text='True이면 건물 출입구로서 ElevatorNode 연결 대상이 됨', verbose_name='건물 출입구 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '노드',
                'verbose_name_plural': '노드 목록',
                'db_table': 'nav_node',
            },
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='장애물 고유 식별자', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(help_text='관리자가 지도에서 그린 장애물 영역. Polygon(면), LineString(선), MultiPolygon(복합 면) 모두 허용', srid=4326, verbose_name='장애물 영역(Geometry)')),
                ('obstacle_type', models.CharField(choices=[('STAIRS', '계단'), ('STEEP_SLOPE', '급경사'), ('CONSTRUCTION', '공사 구간'), ('UNPAVED', '비포장 구간'), ('NARROW_PATH', '협소 통로'), ('OTHER', '기타')], default='OTHER', help_text='계단(STAIRS), 급경사(STEEP_SLOPE), 공사 구간 등', max_length=20, verbose_name='장애물 종류')),
                ('name', models.CharField(blank=True, default='', help_text="예: '공학관 뒤편 계단', '정문 언덕 급경사'", max_length=200, verbose_name='장애물 이름')),
                ('description', models.TextField(blank=True, default='', help_text='장애물에 대한 추가 설명 (관리자 참고용)', verbose_name='상세 설명')),
                ('is_active', models.BooleanField(default=True, help_text='False 로 설정하면 라우팅 제외 대상에서 임시 해제', verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '장애물',
                'verbose_name_plural': '장애물 목록',
                'db_table': 'nav_obstacle',
            },
        ),
        migrations.CreateModel(
            name='ElevatorNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='엘리베이터 노드 고유 식별자', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="예: '공학관 1동 엘리베이터', '지하철역 3번 출구 E/V'", max_length=200, verbose_name='엘리베이터 이름')),
                ('building_name', models.CharField(blank=True, default='', help_text='엘리베이터가 소속된 건물 이름', max_length=200, verbose_name='건물명')),
                ('available_floors', models.CharField(blank=True, default='', help_text="운행 가능한 층 목록 (예: 'B2,B1,1,2,3,4,5')", max_length=100, verbose_name='운행 층 정보')),
                ('is_available', models.BooleanField(default=True, help_text='고장·점검 등으로 사용 불가 시 False 로 설정하면 라우팅에서 제외', verbose_name='사용 가능 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('node', models.OneToOneField(help_text='이 엘리베이터가 위치한 Node (1:1 관계)', on_delete=django.db.models.deletion.CASCADE, related_name='elevator', to='navigation.node', verbose_name='연결 노드')),
            ],
            options={
                'verbose_name': '엘리베이터 노드',
                'verbose_name_plural': '엘리베이터 노드 목록',
                'db_table': 'nav_elevator_node',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='간선 고유 식별자 (UUID v4)', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, help_text='두 노드를 잇는 실제 보행 경로의 선형 데이터', srid=4326, verbose_name='경로 선형(LineString)')),
                ('length', models.FloatField(default=0.0, help_text='LineString의 실제 길이(미터). save() 시 자동 계산됨', verbose_name='물리적 거리(m)')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='True이면 양방향, False이면 source→target 단방향만 가능', verbose_name='양방향 통행 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('source', models.ForeignKey(help_text='이 간선의 시작 지점 (Node FK)', on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='navigation.node', verbose_name='출발 노드')),
                ('target', models.ForeignKey(help_text='이 간선의 끝 지점 (Node FK)', on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='navigation.node', verbose_name='도착 노드')),
            ],
            options={
                'verbose_name': '간선',
                'verbose_name_plural': '간선 목록',
                'db_table': 'nav_edge',
                'indexes': [models.Index(fields=['source', 'target'], name='idx_edge_src_tgt')],
            },
        ),
    ]
